// Generated by LiveScript 1.2.0
(function(){
  var util, ddb, node, people;
  util = require('util');
  ddb = require('ddb');
  node = new ddb.Node;
  people = [['John', 'Doe']].map(function(arg$){
    var firstName, lastName;
    firstName = arg$[0], lastName = arg$[1];
    return ddb.cell(node, {
      firstName: ddb.cell(firstName),
      lastName: ddb.cell(firstName)
    });
  });
  console.log(util.inspect(node.cells, {
    depth: null
  }));
  console.log(people.map(function(it){
    return it.buffer.toString();
  }));
}).call(this);
